"""create apps

Revision ID: 7a32683c6f72
Revises: 
Create Date: 2023-05-15 11:48:48.779207

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '7a32683c6f72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email_id', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', 'O', name='gender'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_id_'), ['id_'], unique=False)

    op.create_table('categories',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id_'), ['id_'], unique=False)

    op.create_table('books',
    sa.Column('id_', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('category_id_', sa.Integer(), nullable=False),
    sa.Column('author_id_', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id_'], ['categories.id_'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id_'], ['authors.id_'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_id_'), ['id_'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_id_'))

    op.drop_table('books')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id_'))

    op.drop_table('categories')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_id_'))

    op.drop_table('authors')
    # ### end Alembic commands ###
